version: '3'
services:
  thynkray-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thynkray-server
    ports:
      - '6001:6001'
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/prisma
    env_file:
      - .env
