export const categories = [
  "All Categories",
  "News",
  "Opinion",
  "International",
  "How-to Guides",
  "Reviews",
  "Tutorials",
  "Personal Stories",
  "Business",
  "Entrepreneurship",
  "Startups",
  "Marketing",
  "Finance",
  "Leadership",
  "Management",
  "Technology",
  "Software Development",
  "AI & Machine Learning",
  "Web Development",
  "Cybersecurity",
  "Blockchain",
  "Lifestyle",
  "Health & Wellness",
  "Travel",
  "Food & Cooking",
  "Relationships",
  "Fitness",
  "Creative",
  "Design",
  "Art",
  "Photography",
  "Music",
  "Writing",
  "Education",
  "Learning",
  "Career Advice",
  "Study Tips",
  "Language Learning",
  "Science",
  "Environment",
  "Politics",
  "Culture",
  "Sports",
  "Gaming",
  "Parenting",
  "Fashion",
  "Movies & TV",
  "History",
  "Philosophy",
  "Psychology",
];
