const categoriesData = [
  "All Categories",
  "News",
  "Opinion",
  "International",
  "How-to Guides",
  "Reviews",
  "Tutorials",
  "Deep Learning",
  "Natural Language Processing",
  "Data Science",
  "Personal Stories",
  "Data Engineering",
  "Data Visualization",
  "Business",
  "Cloud Computing",
  "Serverless Architecture",
  "Microservices",
  "Software Architecture",
  "Clean Code",
  "Software Testing",
  "Test-Driven Development",
  "Functional Programming",
  "Object-Oriented Programming",
  "Domain-Driven Design",
  "Agile Development",
  "Scrum",
  "OAuth",
  "WebSockets",
  "Real-time Applications",
  "Progressive Web Apps",
  "Backend",
  "Kanban",
  "CI/CD",
  "Docker",
  "Kubernetes",
  "Infrastructure as Code",
  "Ansible",
  "Terraform",
  "Web Essentials",
  "Programming",
  "Backend Development",
  "Frontend Development",
  "Full Stack Development",
  "Full Stack Web Development",
  "Full Stack Engineering",
  "Frontend",
  "DevOps",
  "Engineer",
  "Engineering",
  "Tools",
  "Entrepreneurship",
  "Startups",
  "Marketing",
  "Finance",
  "Leadership",
  "Artificial Intelligence",
  "Machine Learning",
  "Management",
  "Technology",
  "Software Development",
  "AI & Machine Learning",
  "Web Development",
  "Cybersecurity",
  "Web Security",
  "Ethical Hacking",
  "Authentication & Authorization",
  "Blockchain",
  "Lifestyle",
  "Health & Wellness",
  "Travel",
  "Food & Cooking",
  "Relationships",
  "Fitness",
  "Creative",
  "Design",
  "Art",
  "Photography",
  "Music",
  "Writing",
  "Education",
  "Learning",
  "Career Advice",
  "Study Tips",
  "Language Learning",
  "Science",
  "Environment",
  "Politics",
  "Culture",
  "Sports",
  "Gaming",
  "Parenting",
  "Fashion",
  "Movies & TV",
  "History",
  "Philosophy",
  "Psychology",
  "WebAssembly",
  "Browser Internals",
  "Performance Optimization",
  "Code Splitting",
  "Lazy Loading",
  "Bundlers & Compilers",
  "Webpack",
  "Vite",
  "Babel",
  "Monorepos",
  "Module Federation",
  "Package Managers",
  "NPM/Yarn/PNPM",
  "Mobile Development",
  "React Native",
  "Flutter",
  "SwiftUI",
  "Android Development",
  "Cross-Platform Development",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "Blockchain",
  "Smart Contracts",
  "Web3",
  "NFT Development",
  "Cryptocurrency",
  "Decentralized Apps (DApps)",
  "GraphQL",
  "REST vs GraphQL",
  "API Gateways",
  "Content Management Systems",
  "Headless CMS",
  "JAMstack",
  "Static Site Generation",
  "Markdown-based Blogging",
  "SaaS Product Development",
  "Startup Engineering",
  "Freelancing as a Developer",
  "Freelancing",
  "Developer Productivity",
  "Time Management for Developers",
  "Remote Work",
  "Technical Writing",
  "Documentation Best Practices",
  "Open Source Contributions",
  "DevRel (Developer Relations)",
  "Community Building",
  "Mentorship in Tech",
  "Tech Interview Prep",
  "System Design",
  "Competitive Programming",
  "Algorithm Design",
  "Data Structures",
  "Big Data",
  "Event-Driven Architecture",
  "Messaging Queues (Kafka/RabbitMQ)",
  "NoSQL Databases",
  "Graph Databases",
  "Caching Strategies",
  "Redis Deep Dive",
  "Observability",
  "Logging & Monitoring",
  "Sentry/Datadog",
  "Feature Flags",
  "A/B Testing",
  "Product Analytics",
  "Tech Ethics",
  "Developer Career Paths",
  "Teaching Code",
  "Hardware Programming (IoT)",
  "Arduino Projects",
  "Raspberry Pi Projects",
  "Robotics Programming",
  "Embedded Systems",
  "Quantum Computing",
];

const removeDuplicates = <T>(array: T[]): T[] => {
  return [...new Set(array)];
};

export const categories = removeDuplicates(categoriesData);
