import { Comment } from "@/modules/comment/types";

export const comments: Comment[] = [
  {
    id: "c1",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u1",
      name: "Alice Johnson",
      profile_image: "/profiles/alice.jpg",
    },
    content:
      "This is exactly the kind of innovation the world needs right now.",
    createdAt: new Date("2025-04-25T10:15:00Z"),
    updatedAt: new Date("2025-04-25T10:15:00Z"),
  },
  {
    id: "c2",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u2",
      name: "Marcus Lee",
      profile_image: "/profiles/marcus.jpg",
    },
    content:
      "Incredible insights on how engineering can shape a greener future.",
    createdAt: new Date("2025-04-09T11:02:00Z"),
    updatedAt: new Date("2025-04-09T11:02:00Z"),
  },
  {
    id: "c3",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u3",
      name: "Priya Desai",
      profile_image: "/profiles/priya.jpg",
    },
    content: "I appreciate the emphasis on renewable materials.",
    createdAt: new Date("2025-04-15T11:35:00Z"),
    updatedAt: new Date("2025-04-28T11:35:00Z"),
  },
  {
    id: "c4",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: { id: "u4", name: "Liam Chen", profile_image: "/profiles/liam.jpg" },
    content: "Well-researched and clearly written. Thanks for sharing!",
    createdAt: new Date("2025-04-20T12:00:00Z"),
    updatedAt: new Date("2025-04-28T12:00:00Z"),
  },
  {
    id: "c5",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u5",
      name: "Sofia Martínez",
      profile_image: "/profiles/sofia.jpg",
    },
    content: "This could be a game-changer in urban development.",
    createdAt: new Date("2025-04-18T12:18:00Z"),
    updatedAt: new Date("2025-04-28T12:18:00Z"),
  },
  {
    id: "c6",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: { id: "u6", name: "David Kim", profile_image: "/profiles/david.jpg" },
    content: "Curious to see how these solutions scale globally.",
    createdAt: new Date("2025-04-01T12:34:00Z"),
    updatedAt: new Date("2025-04-28T12:34:00Z"),
  },
  {
    id: "c7",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u7",
      name: "Fatima Zahra",
      profile_image: "/profiles/fatima.jpg",
    },
    content: "The future of sustainability starts with informed engineering!",
    createdAt: new Date("2025-04-28T13:00:00Z"),
    updatedAt: new Date("2025-04-28T13:00:00Z"),
  },
  {
    id: "c8",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: { id: "u8", name: "Noah Smith", profile_image: "/profiles/noah.jpg" },
    content: "How can startups contribute to these sustainable practices?",
    createdAt: new Date("2025-04-28T13:15:00Z"),
    updatedAt: new Date("2025-04-28T13:15:00Z"),
  },
  {
    id: "c9",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u9",
      name: "Isabella Rossi",
      profile_image: "/profiles/isabella.jpg",
    },
    content: "Loved the section on modular construction methods!",
    createdAt: new Date("2025-04-28T13:27:00Z"),
    updatedAt: new Date("2025-04-28T13:27:00Z"),
  },
  {
    id: "c10",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u10",
      name: "Oliver Green",
      profile_image: "/profiles/oliver.jpg",
    },
    content: "We need more engineers thinking like this!",
    createdAt: new Date("2025-04-28T13:42:00Z"),
    updatedAt: new Date("2025-04-28T13:42:00Z"),
  },
  {
    id: "c11",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u11",
      name: "Emma Davis",
      profile_image: "/profiles/emma.jpg",
    },
    content: "Important topic, and excellently discussed.",
    createdAt: new Date("2025-04-28T14:00:00Z"),
    updatedAt: new Date("2025-04-28T14:00:00Z"),
  },
  {
    id: "c12",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u12",
      name: "Mohammed Khan",
      profile_image: "/profiles/mohammed.jpg",
    },
    content: "Does this apply to transportation systems too?",
    createdAt: new Date("2025-04-28T14:20:00Z"),
    updatedAt: new Date("2025-04-28T14:20:00Z"),
  },
  {
    id: "c13",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u13",
      name: "Chloe Nguyen",
      profile_image: "/profiles/chloe.jpg",
    },
    content: "I learned so much from this. Thank you!",
    createdAt: new Date("2025-04-28T14:35:00Z"),
    updatedAt: new Date("2025-04-28T14:35:00Z"),
  },
  {
    id: "c14",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: {
      id: "u14",
      name: "Jasper Müller",
      profile_image: "/profiles/jasper.jpg",
    },
    content: "Could you recommend further reading on this topic?",
    createdAt: new Date("2025-04-28T14:45:00Z"),
    updatedAt: new Date("2025-04-28T14:45:00Z"),
  },
  {
    id: "c15",
    post: { id: "p1", title: "Pioneering sustainable engineering solutions" },
    user: { id: "u15", name: "Sara Ali", profile_image: "/profiles/sara.jpg" },
    content: "We need more engineers to focus on long-term impacts.",
    createdAt: new Date("2025-04-29T15:00:00Z"),
    updatedAt: new Date("2025-04-28T15:00:00Z"),
  },
];
